version: "2"

volumes:
  db-data:
    external: false

services:
  cache:
    image: memcached:1.4-alpine

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: DemoProject_development
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
  jobs:
    env_file: .env
    build: .
    volumes:
      - .:/DemoProject
    command: bundle exec rake jobs:work
    depends_on:
      - db
  app:
    env_file: .env
    build: .
    command: build exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/DemoProject"
    ports:
      - "3001:3000"
    depends_on:
      - db
