version: "3.7"
services:
  app:
    image: bilalfayyaz93/shopping101:4.1
    command: /bin/sh -c "rm -f /tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopping101_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

