version: "3.7"
services:
  app:
    image: bilalfayyaz93/shopping101:1.4
    command: /bin/sh -c "rm -f /tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: shopping101_db
      DB_HOST: mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: shopping101_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    expose:
      - '3306'
